// Mirror of node-types.ts BROWSER_EVENTS — no Node.js deps, safe for browser bundle
export const BROWSER_EVENTS = {
  FETCH_STARTED:           'observer.browser/network.request.started',
  FETCH_COMPLETED:         'observer.browser/network.request.completed',
  FETCH_FAILED:            'observer.browser/network.request.failed',
  XHR_STARTED:             'observer.browser/network.xhr.started',
  XHR_COMPLETED:           'observer.browser/network.xhr.completed',
  XHR_FAILED:              'observer.browser/network.xhr.failed',
  WS_OPENED:               'observer.browser/network.ws.opened',
  WS_CLOSED:               'observer.browser/network.ws.closed',
  WS_MESSAGE_SENT:         'observer.browser/network.ws.message.sent',
  WS_MESSAGE_RECEIVED:     'observer.browser/network.ws.message.received',
  CONSOLE_LOG:             'observer.browser/console.log',
  CONSOLE_WARN:            'observer.browser/console.warn',
  CONSOLE_ERROR:           'observer.browser/console.error',
  CONSOLE_INFO:            'observer.browser/console.info',
  CONSOLE_DEBUG:           'observer.browser/console.debug',
  CONSOLE_GROUP:           'observer.browser/console.group',
  EXCEPTION:               'observer.browser/exception.uncaught',
  UNHANDLED_REJECTION:     'observer.browser/exception.unhandled_rejection',
  NAVIGATION_PUSH:         'observer.browser/navigation.push',
  NAVIGATION_POP:          'observer.browser/navigation.pop',
  NAVIGATION_REPLACE:      'observer.browser/navigation.replace',
  NAVIGATION_LOAD:         'observer.browser/navigation.load',
  NAVIGATION_HASH:         'observer.browser/navigation.hash',
  DOM_CLICK:               'observer.browser/dom.click',
  DOM_INPUT:               'observer.browser/dom.input',
  DOM_SUBMIT:              'observer.browser/dom.submit',
  PERFORMANCE_MARK:        'observer.browser/performance.mark',
  PERFORMANCE_MEASURE:     'observer.browser/performance.measure',
  LONG_TASK:               'observer.browser/performance.long_task',
} as const;
