import type { RuntimeNode, RuntimeEvent } from '@observer-os/core';
import type { ContextPackage, RankedNode, RankedEvent } from '../types.js';

export function renderMarkdown(pkg: Omit<ContextPackage, 'markdownContent' | 'tokenEstimate'>): string {
  const lines: string[] = [];

  lines.push('# Observer OS — Runtime Context Package');
  lines.push('');
  lines.push(`**Session:** \`${pkg.sessionId}\``);
  lines.push(`**Anchor:** ${pkg.anchor.type} → \`${pkg.anchor.nodeId}\``);
  lines.push(`**Generated:** ${new Date(pkg.generatedAt).toISOString()}`);
  lines.push(`**Depth:** ${pkg.depth}`);
  lines.push('');

  // Causal chain
  if (pkg.causalChain.length > 0) {
    lines.push('## Causal Chain');
    lines.push('');
    lines.push('Root cause propagation path:');
    lines.push('');
    const anchorsMap = new Map(pkg.nodes.map((rn) => [rn.node.id as string, rn.node]));
    pkg.causalChain.forEach((id, idx) => {
      const node = anchorsMap.get(id);
      const prefix = idx === 0 ? '→ [ROOT]' : `→ [hop ${idx}]`;
      if (node) {
        lines.push(`${prefix} \`${node.type}\` (\`${id}\`) — status: **${node.status}**`);
      } else {
        lines.push(`${prefix} \`${id}\``);
      }
    });
    lines.push('');
  }

  // Cross-domain correlations
  if (pkg.correlatedNodes.length > 0) {
    lines.push('## Cross-Domain Correlations');
    lines.push('');
    const nodeMap = new Map(pkg.nodes.map((rn) => [rn.node.id as string, rn.node]));
    for (const id of pkg.correlatedNodes) {
      const node = nodeMap.get(id);
      if (node) {
        lines.push(`- \`${node.type}\` in domain **${node.domain}** (\`${id}\`)`);
      } else {
        lines.push(`- \`${id}\``);
      }
    }
    lines.push('');
  }

  // Top nodes by relevance
  lines.push('## Relevant Nodes');
  lines.push('');

  for (const rn of pkg.nodes.slice(0, 10)) {
    lines.push(renderNode(rn));
    lines.push('');
  }

  // Top events by relevance
  if (pkg.events.length > 0) {
    lines.push('## Relevant Events');
    lines.push('');
    lines.push('| # | Time | Type | Severity | Node |');
    lines.push('|---|------|------|----------|------|');

    for (const re of pkg.events.slice(0, 20)) {
      const e = re.event;
      const ts = e.occurredAt || e.recordedAt || 0;
      const time = ts ? new Date(ts).toISOString().split('T')[1]?.slice(0, 12) ?? '' : '?';
      lines.push(`| ${re.rank} | ${time} | \`${e.type}\` | ${e.severity} | \`${e.sourceNodeId.slice(0, 20)}\` |`);
    }
    lines.push('');
  }

  // Source frames (from anchor error stack)
  if (pkg.sourceFrames.length > 0) {
    lines.push('## Stack Trace');
    lines.push('');
    for (const f of pkg.sourceFrames.slice(0, 15)) {
      lines.push(`→ \`${f.fn}\`  ${f.file}:${f.line}:${f.column}`);
    }
    lines.push('');
  }

  // Error details (if anchor is an error node)
  const anchorNode = pkg.nodes.find((rn) => rn.node.id === pkg.anchor.nodeId)?.node;
  if (anchorNode?.status === 'FAILED') {
    lines.push('## Error Details');
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(anchorNode.metadata, null, 2));
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Observer OS Context Engine*');

  return lines.join('\n');
}

function renderNode(rn: RankedNode): string {
  const n = rn.node;
  const lines: string[] = [];

  lines.push(`### [#${rn.rank}] \`${n.type}\` — ${n.domain} (score: ${rn.relevanceScore})`);
  lines.push(`- **ID:** \`${n.id}\``);
  lines.push(`- **Status:** ${n.status}`);
  lines.push(`- **Reason:** ${rn.reason}`);

  if (Object.keys(n.metadata).length > 0) {
    const preview = Object.entries(n.metadata)
      .slice(0, 5)
      .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
      .join(', ');
    lines.push(`- **Metadata:** \`${preview}\``);
  }

  if (n.relationships.length > 0) {
    const relSummary = n.relationships
      .slice(0, 4)
      .map((r) => `${r.type} → ${r.target.slice(0, 20)}`)
      .join('; ');
    lines.push(`- **Relationships:** ${relSummary}`);
  }

  return lines.join('\n');
}

export function estimateTokens(text: string): number {
  // ~4 chars per token (rough GPT-style estimate)
  return Math.ceil(text.length / 4);
}
